# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Avner Bensoussan"
first_name: "Avner"
middle_name:
last_name: "Bensoussan"
contact_note:
  "You can reach me at this <a href='mailto:avner.bensoussan@kcl.ac.uk'>email</a>."
description: ""
footer_text: ""
keywords:
  "Hybrid Quantum-Classical Architectures, Quantum Software Testability, Fault Understanding, Quantum Information Theory"
lang: "en"
icon: "⚛️"

url: "https://avnerbensoussan.github.io"
baseurl:
last_updated: false
impressum_path: ""
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: "default"
repo_theme_dark: "dark"
repo_trophies:
  enabled: false
  theme_light: "flat"
  theme_dark: "gitdimmed"

external_services:
  github_readme_stats_url: "https://github-readme-stats.vercel.app"
  github_profile_trophy_url: "https://github-profile-trophy.vercel.app"

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: false
bib_search: true

max_width: "930px"

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image: null

# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------

google_analytics: null
cronitor_analytics: null
pirsch_analytics: null
openpanel_analytics: null

google_site_verification: null
bing_site_verification: null

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: "al-folio"
blog_description: "a simple whitespace theme for academics"
permalink: "/blog/:year/:title/"
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo: null
  repo_id: null
  category: "Comments"
  category_id: null
  mapping: "title"
  strict: 1
  reactions_enabled: 1
  input_position: "bottom"
  dark_theme: "dark"
  light_theme: "light"
  emit_metadata: 0
  lang: "en"

disqus_shortname: "al-folio"

external_sources:
  - name: "medium.com"
    rss_url: "https://medium.com/@al-folio/feed"
    categories:
      - "external-posts"
    tags:
      - "medium"
  - name: "Google Blog"
    posts:
      - url:
          "https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/"
        published_date: "2024-05-14"
    categories:
      - "external-posts"
    tags:
      - "google"

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint: null

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: "post"
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: "kramdown"
highlighter: "rouge"
kramdown:
  input: "GFM"
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include:
  - "_pages"
  - "_scripts"

exclude:
  - "bin/"
  - "CONTRIBUTING.md"
  - "CUSTOMIZE.md"
  - "Dockerfile"
  - "docker-compose.yml"
  - "docker-compose-slim.yml"
  - "FAQ.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "INSTALL.md"
  - "LICENSE"
  - "lighthouse_results/"
  - "package.json"
  - "package-lock.json"
  - "_pages/about_einstein.md"
  - "purgecss.config.js"
  - "README.md"
  - "readme_preview/"
  - "vendor"

keep_files:
  - "CNAME"
  - ".nojekyll"

plugins:
  - "jekyll-3rd-party-libraries"
  - "jekyll-archives-v2"
  - "jekyll-cache-bust"
  - "jekyll-email-protect"
  - "jekyll-feed"
  - "jekyll-get-json"
  - "jekyll-imagemagick"
  - "jekyll-jupyter-notebook"
  - "jekyll-link-attributes"
  - "jekyll-minifier"
  - "jekyll-paginate-v2"
  - "jekyll-regex-replace"
  - "jekyll/scholar"
  - "jekyll-sitemap"
  - "jekyll-socials"
  - "jekyll-tabs"
  - "jekyll-terser"
  - "jekyll-toc"
  - "jekyll-twitter-plugin"
  - "jemoji"

# -----------------------------------------------------------------------------
# Filtered bibtex keywords
# -----------------------------------------------------------------------------

filtered_bibtex_keywords:
  - "abbr"
  - "abstract"
  - "additional_info"
  - "altmetric"
  - "annotation"
  - "arxiv"
  - "award"
  - "award_name"
  - "bibtex_show"
  - "blog"
  - "code"
  - "dimensions"
  - "eprint"
  - "google_scholar_id"
  - "hal"
  - "html"
  - "inspirehep_id"
  - "pdf"
  - "pmid"
  - "poster"
  - "preview"
  - "selected"
  - "slides"
  - "supp"
  - "video"
  - "website"

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: "resume"
    json: "assets/json/resume.json"

jsonresume:
  - "basics"
  - "work"
  - "education"
  - "publications"
  - "projects"
  - "volunteer"
  - "awards"
  - "certificates"
  - "skills"
  - "languages"
  - "interests"
  - "references"
